version: "3.3"

networks:
  geocache:
  nginxnetwork:

volumes:
  geoserver-data:
  geo-db-data:

services:
  nginx:
    container_name: nginx_urbverde
    image: nginx:1.21.6-alpine
    volumes:
      - ./sites-enabled/nginx2.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
      - /etc/letsencrypt/:/etc/letsencrypt/

    logging:
      driver: json-file
      options:
        max-size: 200m
        max-file: "10"
    depends_on:
      - sphere-tileserv
      - geoserver
      - cache
    restart: on-failure

    networks:
      - nginxnetwork

    ports:
      - "80:80"
      - "443:443"

  db:
    container_name: db_urbverde
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    volumes:
      - geo-db-data:/var/lib/postgresql
      - ./certs-db/:/ssl_certificates/

    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      - SSL_CERT_FILE=/ssl_certificates/ca.pem
      - SSL_KEY_FILE=/ssl_certificates/private_key.pem
    restart: on-failure
    healthcheck:
      test: "exit 0"
    networks:
      - nginxnetwork

  sphere-tileserv:
    image: pramsey/pg_tileserv:latest-alpine-3.12
    container_name: sphere-tileserv
    build:
      context: ./pg_tileserv
      dockerfile: Dockerfile.alpine
      args:
        VERSION: latest-alpine-3.12

    environment:
      - DATABASE_URL=${DATABASE_URL}

    ports:
      - 7800:7800

    networks:
      - geocache
      - nginxnetwork

  geoserver:
    container_name: geoserver_urbverde
    image: kartoza/geoserver:${GS_VERSION}
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - ./certs:/etc/certs
      - ./raster-data:/opt/geoserver/data_dir/workspaces/urbverde/raster-data
    restart: on-failure
    environment:
      - SSL=true
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - HTTPS_PROXY_NAME=urbverde.iau.usp.br
      - HTTP_SCHEME=https

    depends_on:
      - db
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

    ports:
      - 8080:8443

    networks:
      - nginxnetwork

  cache:
    image: eeacms/varnish
    ports:
      - 6081:6081
    environment:
      BACKENDS: "sphere-tileserv:7800"
      DNS_ENABLED: "false"
      COOKIES: "true"
      PARAM_VALUE: "-p default_ttl=600"
    networks:
      - geocache
      - nginxnetwork
    depends_on:
      - sphere-tileserv
